#!/bin/bash

module load plink/1.90b6.21
module load R

DATA=/projectnb/bs859/data/RheumatoidArthritis/final_project

# check sex assignments
plink --bfile $DATA/narac_hg19 --check-sex --set-hh-missing --out sexstat
## Warning: 10855 het. haploid genotypes present (see freq1.hh ); many commands treat these as missing.
### heterozygous haploid and nonmale Y chromosome genotype calls are logged to plink.hh and treated as missing by all analysis commands, 
### but left undisturbed by --make-bed

# select individuals with sex problem
grep "PROBLEM" sexstat.sexcheck > fail_sex_check.txt

# remove failed sex individuals
plink --bfile $DATA/narac_hg19 --remove fail_sex_check.txt --make-bed --out narac-sex_problems

## Turner et al. (2011) recommend removing poor-quality SNPs before running the sample genotyping efficiency,
## so that fewer samples will be dropped from the analysis simply because they were genotyped with SNP assays that had poor performance
# create filtered genotype
plink --bfile narac-sex_problems --maf 0.01 --geno 0.05 --hwe 1e-6 --not-chr X --make-bed --out narac_almost
#Warning: 3 het. haploid genotypes present (see narac_almost.hh ); many commands
#treat these as missing.
#Warning: Nonmissing nonmale Y chromosome genotype(s) present; many commands
#treat these as missing.
#Total genotyping rate is 0.992656.
#18285 variants removed due to missing genotype data (--geno).
#--hwe: 660 variants removed due to Hardy-Weinberg exact test.
#22054 variants removed due to minor allele threshold(s)
#(--maf/--max-maf/--mac/--max-mac).
#490085 variants and 2055 people pass filters and QC.

#remove individuals 
plink --bfile narac_almost --mind 0.05 -make-bed --out narac_final
#0 people removed due to missing genotype data (--mind).

# check for individuals with elevated missing data rates or extremely high/low heterozygosity rate
plink --bfile narac_final --het --out het

# compute allele frequencies
plink --bfile narac_final --freq --out freq
plink --bfile narac_final --freqx --out freqx

# compute missing rates for individuals and variants
plink --bfile narac_final --missing --out miss

# compute hardy-weinberg test for each variant
plink --bfile narac_final --hardy --out hwe

# SNPs with hwe p<0.0001 in unaffected
awk '($3=="UNAFF"&&$9<0.0001)||NR==1{print $0}'  hwe.hwe>hwe.unaff.0001.txt
## 449 variants with p<0.0001 for the HWE test using unaffected controls

awk 'NR==1||$6>0.03{print $0}' miss.imiss>highmissingindiv.txt
## 19 individuals who have missing genotype rates >3% (call rate <97%)

# remove high missing individuals
plink --bfile narac_final --remove highmissingindiv.txt --make-bed --out narac-no_missing

# check missingness
plink --bfile narac-no_missing --test-missing --out cctest
#319748 snps with missing data

#SNPs with small p-values
awk 'NR==1||($5 < 0.05) {print $0}' cctest.missing >cctest05.missing
#40777 snps with small p-val

#variants with a lot of missingness between cases and controls are cause for concern
#if missingness is not random by genotype this could induce an association so let's remove them
plink --bfile narac-no_missing --exclude cctest05.missing --make-bed --out narac_no_miss

#compute heterozygote deficit
plink --bfile narac_no_miss --het --out Fstat
R --vanilla<Fstat.R>Fstat.log
#      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
#-0.0269400 -0.0009348  0.0038770  0.0042202  0.0089215  0.0785200 
h
#no real obvious relationship between missingness and Fstat

plink --bfile narac_no_miss --test-mishap --out narac_no_genomiss


