#!/bin/bash

module load plink/1.90b6.21
module load R

DATA=/projectnb/bs859/data/RheumatoidArthritis/final_project

plink --bfile $DATA/narac_hg19 --set-hh-missing --make-bed --out narac

plink --bfile narac --freq --out freq

plink --bfile narac --missing --out miss

plink --bfile narac --hardy --out hwe

plink --bfile narac --check-sex --out sexstat
#Total genotyping rate is 0.99268.
#544276 variants and 2062 people pass filters and QC.
#Among remaining phenotypes, 868 are cases and 1194 are controls.
#--check-sex: 13098 Xchr and 0 Ychr variant(s) scanned, 5 problems detected.

grep "PROBLEM" sexstat.sexcheck > fail_sex_check.txt

# remove failed sex individuals
plink --bfile narac --remove fail_sex_check.txt --make-bed --out narac_sex

awk '($3=="UNAFF"&&$9<0.000001||NR==1{print $0}' hwe.hwe>hwe.unaff.000001.txt

awk 'NR==1||$6>0.03{print $0}' miss.imiss>highmissingindiv.txt

plink --bfile narac_sex --maf 0.01 --geno 0.05 --hwe 1e-6 --not-chr X --make-bed --out narac_sex2
#Total genotyping rate is 0.992656.
#18313 variants removed due to missing genotype data (--geno).
#--hwe: 663 variants removed due to Hardy-Weinberg exact test.
#22054 variants removed due to minor allele threshold(s)


plink --bfile narac_sex2 --mind 0.05 -make-bed --out narac_sex3
#0 people removed due to missing genotype data (--mind).

# check for individuals with elevated missing data rates or extremely high/low heterozygosity rate
plink --bfile narac_sex3 --het --out het

plink --bfile narac_sex3 --remove highmissingindiv.txt --make-bed --out narac_sex4

plink --bfile narac_sex4 --test-missing --out cctest
#313687 snps with missing data

#SNPs with small p-values
awk 'NR==1||($5 < 0.05) {print $0}' cctest.missing >cctest05.missing
#40970 snps with small p-val
awk '$5 < 0.05 {print $2}' cctest.missing >SNP_List.txt

#variants with a lot of missingness between cases and controls are cause for concern
#if missingness is not random by genotype this could induce an association so let's remove them
plink --bfile narac_sex4 --exclude SNP_List.txt --make-bed --out narac_sex5
#--exclude: 449084 variants remaining.

plink --bfile narac_sex5 --het --out Fstat
R --vanilla<Fstat.R>Fstat.log
#      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
#-0.0269300 -0.0009296  0.0038840  0.0041924  0.0088880  0.0784300 

plink --bfile narac_sex5 --indep-pairwise 10000 5000 0.2 --out idpw

plink --bfile narac_sex5 –-exclude idpw.prune.out --genome --min 0.05 --out related
#--exclude: 98845 variants remaining.
#Using up to 27 threads (change this with --threads).
#Before main variant filters, 2030 founders and 0 nonfounders present.
#Calculating allele frequencies... done.
#Total genotyping rate is 0.997239.
#98845 variants and 2030 people pass filters and QC.
#Among remaining phenotypes, 853 are cases and 1177 are controls.
#Excluding 2 variants on non-autosomes from IBD calculation.
#IBD calculations complete.  
#awk '$10>0.05{print $0}' ibd05.genome > ibd.gt05.genome

#16 relationships
#make list of ids to remove from data
awk '{print $2}' related.genome >iid1.txt
awk '(NR>1)' iid1.txt>IID1.txt
awk '{print $4}' related.genome >iid2.txt
awk '(NR>1)' iid1.txt>IID2.txt

sort -u IID1.txt IID2.txt >related_list.txt

plink --bfile narac_sex5 --exclude related_list.txt --make-bed --out narac_qc


#end data is narac_qc

